config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  resources :events
  resources :friendships
  resources :profiles
  get 'users/show'
  get 'users/friends'

  resources :posts do
    resource :like, module: :posts
    member do
      post :share
    end
  end

  devise_for :users
  resources :users, :only => [:show, :friends] do
    resources :pictures do
      resource :like, module: :pictures
      member do
        post :share
      end
    end
    resources :albums
  end
  
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  
  root :to => redirect('/events')

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :pictures
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /albums
  # GET /albums.json
  def index
    @albums = @user.albums
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @pictures = @album.pictures
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)
    @album.user_id = @user.id

    respond_to do |format|
      if @album.save
        format.html { redirect_to user_albums_path(@user), notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:user_id, :title, :description)
    end

    def set_user
      @user = User.find(params[:user_id])
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper

  def album_thumbnail(album)
    if album.pictures.count > 0
      image_tag album.pictures.first.location, :class => 'img-responsive'
    else
      image_tag 'http://placehold.it/150x100', :class => 'img-responsive'
    end
  end
end

app/views/albums/_form.html.erb
<%= form_for([@user, @album], :html => {:class => 'form-horizontal'}) do |f| %>
  <% if flash[:errors] %>
    <div class="alert alert-warnings">
      <%= flash[:errors].each do |key, value| %>
        <% value = value[0] %>
	<li><%= "#{key} #{value}" %></li>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-2 text-right">
      <%= f.label :title, :class => "control-label" %><br>
    </div>
    <div class="col-sm-6">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-2 text-right">
      <%= f.label :description, :class => "control-label" %><br>
    </div>
    <div class="col-sm-6">
      <textarea name="album[description]" id="album_description" class="form-control" rows="5"></textarea>
    </div>
  </div>
  <div class="form-group actions">
    <div class="col-sm-2"></div>
    <div class="col-sm-10">
      <button type="submit" class="btn btn-default">Create Album</button>
    </div>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Albums</h1>
<%= @albums.in_groups_of(4, false) do |albums| %>
  <div class="row">
    <% albums.each do |album| %>
      <div class="col-sm-3">
	<div class="thumbnail">
	  <%= link_to album_thumbnail(album), user_album_path(@user, album) %>
	  <div class="caption text-center">
	    <h3><%= link_to album.title, user_album_path(@user, album) %></h3>
	    <p><%= album.description %></p>
	  </div> <!-- caption -->
	</div> <!-- thumbnail -->
      </div>
    <% end %>
  </div>
<% end %>

<br>

<%= link_to 'New Album', new_user_album_path %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', user_albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @album.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @album.description %>
</p>

<% @pictures.in_groups_of(6, false) do |pictures| %>
  <div class="row image-thum-row">
    <% pictures.each do |picture| %>
      <div class="col-sm-2">
	<%= link_to image_tag(picture.location, :class => 'img-responsive'), user_picture_path(@user, picture) %>
      </div>
    <% end %>
  </div>
<% end %>

<%= link_to 'Edit', edit_user_album_path(@user, @album) %> |
<%= link_to 'Back', user_albums_path(@user) %>