config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  resources :events
  resources :friendships
  resources :profiles
  get 'users/show'
  get 'users/friends'

  resources :posts do
    resource :like, module: :posts
    member do
      post :share
    end
  end

  devise_for :users
  resources :users, :only => [:show, :friends] do
    resources :pictures do
      resource :like, module: :pictures
      member do
        post :share
      end
    end
    resources :albums
  end
  
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  
  root :to => redirect('/events')

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
  belongs_to :album
  has_many :likes, :as => :likable
  has_many :comments, :as => :commentable

  def save_file(tempfile)
    filename = "#{self.id.to_s}.jpg"
    folder = "#{Rails.root}/public/uploads/users/#{self.user_id}"
    
    FileUtils::mkdir_p folder

    f = File.open File.join(folder, filename), "wb"
    f.write tempfile.read()
    f.close

    update location: "/uploads/users/#{self.user_id}/#{filename}"
  end

  def mentions
    @mentions ||= begin
                    regex = /@([\w]+\@[\w]+\.[\w]+)/
                    caption.scan(regex).flatten
                  end
  end

  def mentioned_users
    @mentioned_users ||= User.where(email: mentions)
  end

  def notify_mentioned_users
    mentioned_users.each do |user|
      Notification.create(recipient: user, actor_id: self.user_id, action: "tagged", notifiable: self)
    end
  end
end

app/controllers/pictures/likes_controller.rb
class Pictures::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_picture
  before_action :set_user

  def create
    @picture.likes.where(user_id: current_user.id).first_or_create
    current_user.events.create(action: "liked", eventable: @picture)

    respond_to do |format|
      format.html {redirect_to user_picture_path(@user, @picture) }
      format.js
    end
  end

  def destroy
    @picture.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html {redirect_to user_picture_path(@user, @picture) }
      format.js
    end
  end

  private
    def set_picture
      @picture = Picture.find(params[:picture_id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy, :share]
  before_action :set_user

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @comment = Comment.new
    if current_user.id == @user.id
      @profile = Profile.find_or_create_by(user_id: @user.id)
      @album = Album.new
      @albums = @user.albums
    end
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
    @albums = @user.albums
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new
    @picture.user_id = @user.id
    @picture.save
    @picture.save_file(params[:picture][:location])
    @picture.album_id = params[:picture][:album_id]
    @picture.caption = params[:picture][:caption]
    @picture.mentions
    @picture.mentioned_users
    @picture.notify_mentioned_users

    respond_to do |format|
      if @picture.save
        current_user.events.create(action: "added", eventable: @picture)
        format.html { redirect_to user_pictures_path(@user), notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to user_picture_path(@user, @picture), notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def share
    current_user.events.create(action: "shared", eventable: @picture)
    redirect_to events_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:user_id, :location, :album_id, :caption)
    end

    def set_user
      @user = User.find(params[:user_id])
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for([@user, @picture], :html => {:class => "form-horizontal"}) do |f| %>
  <div class="form-group">
    <%= f.label :album_id, "Add to Album", :class => "col-sm-3 control-label" %>
    <div class="col-sm-4">
      <%= f.select "album_id", @albums.collect { |a| [a.title, a.id] }, {include_blank: true}, {:class => "form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :picture, :class => "col-sm-3 control-label" %>
    <div class="col-sm-4">
      <%= f.file_field :location, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :caption, :class => "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <textarea name="picture[caption]" data-behavior="user-mention-field" class="form-control" rows="5"></textarea>
    </div>
  </div>
  <div class="actions">
    <button class="btn btn-default post-submit" type="submit">Add</button>
  </div>


<!--  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
-->
<% end %>

app/views/pictures/_likes.html.erb
<% if user_signed_in? && current_user.likes_picture?(picture) %>
  <%= link_to "Unlike", user_picture_like_path(picture.user, picture), method: :delete, remote: true %>
  <%= link_to "Share", share_user_picture_path(picture.user, picture), method: :post  %>
<% else %>
  <%= link_to "Like", user_picture_like_path(picture.user, picture), method: :post, remote: true %>
  <%= link_to "Share", share_user_picture_path(picture.user, picture), method: :post %>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="btn-group" role="group" aria-label="...">
    <% if user_signed_in? and current_user.id == @user.id %>
      <%= link_to 'Add Pictures', new_user_picture_path, :class => 'btn btn-default' %>
      <% end %>
      <%= link_to 'My Galleries', user_albums_path(@user), :class => 'btn btn-default' %>
    </div>
  </div>

</div> <!-- row -->

<% @pictures.in_groups_of(6, false) do |pictures| %>
  <div class="row image-thumb-row">
    <% pictures.each do |picture| %>
      <div class="col-sm-2">
	<a href="<%= user_picture_path(@user, picture) %>"><img src="<%= picture.location %>" class="img-responsive" ></a>
      </div>
    <% end %>
  </div>
<% end %>

app/views/pictures/new.html.erb
<h4>New Picture</h4>

<%= render 'form' %>

<%= link_to 'Back', user_pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <% if current_user == @user %>
    <div class="col-sm-3">
      <%= form_for(@profile) do |f| %>
        <%= f.hidden_field :user_id, value: @user.id %>
	<%= f.hidden_field :profile_picture_id, value: @picture.id %>
        <button class="btn btn-default" type="submit">Make Profile Image</button>
      <% end %>
    </div>
      
    
    <div class="col-sm-6">
      <%= form_for([@user, @picture], url: user_picture_path, :html => {:class => 'form-inline'}) do |p| %>
        <div class="form-group">
	  <button class="btn btn-default" type="submit">Add to Album</button>
	  <%= p.select "album_id", @albums.collect {|a| [a.title, a.id]}, {}, {:class => "form-control"} %>
	</div>
      <% end %>
    
    </div>
  <% end %>
</div>

<div class="row image-thumb-row">
  <div class="col-sm-12 text-center">
    <%= image_tag @picture.location, :class => 'img-responsive' %>
  
  <div id="picture_<%= @picture.id %>_likes" class="text-left picture-likes">
    <%= render partial: 'pictures/likes', locals: {picture: @picture} %>
    <div id="picture_<%= @picture.id %>_comments">
      <%= render partial: 'comments/comments', locals: {comments: @picture.comments} %>
    </div>
    <%= render partial: 'comments/form', locals: {commentable: @picture} %>
  </div>
  </div>
</div>