config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  resources :events
  resources :friendships
  resources :profiles
  get 'users/show'
  get 'users/friends'

  resources :posts do
    resource :like, module: :posts
    member do
      post :share
    end
  end

  devise_for :users
  resources :users, :only => [:show, :friends] do
    resources :pictures do
      resource :like, module: :pictures
      member do
        post :share
      end
    end
    resources :albums
  end
  
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  
  root :to => redirect('/events')

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :body, :user_id, :presence => true
  has_many :likes, :as => :likable
  has_many :comments, :as => :commentable

  def mentions
    @mentions ||= begin
                    regex = /@([\w]+\@[\w]+\.[\w]+)/
                    body.scan(regex).flatten
                  end
  end

  def mentioned_users
    @mentioned_users ||= User.where(email: mentions)
  end

  def notify_mentioned_users
    mentioned_users.each do |user|
      Notification.create(recipient: user, actor_id: self.user_id, action: "tagged", notifiable: self)
    end
  end

end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @post.likes.where(user_id: current_user.id).first_or_create
    current_user.events.create(action: "liked", eventable: @post)
    
    respond_to do |format|
      format.html { redirect_to posts_path }
      format.js
    end
  end

  def destroy
    @post.likes.where(user_id: current_user.id).destroy_all
    respond_to do |format|
      format.html {redirect_to posts_path }
      format.js
    end
  end

  private
    def set_post
      @post = Post.find(params[:post_id])
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :share]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.last(5).reverse
    @post = params[:post] || Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.body = params[:body]
    @post.user_id = current_user.id
    @post.mentions
    @post.mentioned_users
    @post.notify_mentioned_users
    respond_to do |format|
      if @post.save
        current_user.events.create(action: "posted", eventable: @post)
        format.html { redirect_to events_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { redirect_to posts_path, flash: {errors: @post.errors} }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def share 
    current_user.events.create(action: "shared", eventable: @post)
    redirect_to events_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.fetch(:post, {})
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if flash[:errors] %>
    <div class="alert alert-warning">
      <% flash[:errors].each do |key, value| %>
        <% value = value[0] %>
        <li><%= "#{key} #{value}" %></li>
      <% end %>
      
    </div> <!-- alert alert-warning -->
  <% end %>
<!--  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
-->
  <textarea name="body" class="form-control" data-behavior="user-mention-field" rows="3" placeholder="What are you up to?"></textarea>

  <div class="actions">
    <button class="btn btn-default post-submit" type="submit">Post</button>
    <!--<%= f.submit %> -->
  </div>
<% end %>

app/views/posts/_likes.html.erb
<% if user_signed_in?  && current_user.likes_post?(post) %>
  <%= link_to "Unlike", post_like_path(post), method: :delete, remote: true %>
  <%= link_to "Share", share_post_path(post), method: :post %>
<% else %>
  <%= link_to "Like", post_like_path(post), method: :post, remote: true %>
  <%= link_to "Share", share_post_path(post), method: :post %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<div class="row">
  <div class="col-sm-3">
    <h4>News Feed</h4>
  </div> <!-- col-sm-3-->
  <div class="col-sm-2">
    
  </div> <!-- col-sm-2 -->
  <div class="col-sm-7">
    <%= render 'form' %>
  </div> <!-- col-sm-7 -->
</div> <!-- row -->
<!--
<% @posts.each do |post| %>
  <div class="row main-body-row">
    <div class="col-sm-3"></div>
    <div class="col-sm-2">
      <%= image_tag 'http://placehold.it/60x60' %>
    </div> <!-- col-sm-2 --
    <div class="col-sm-7">
      <p>
	<%= post.body %>
      </p>
    </div> <!-- col-sm-7 --
  </div> <!-- row --
<% end %>
-->
<div class="row main-body-row">
  <div class="col-sm-3"></div>
  <div class="col-sm-9">
    <ul class="media-list">
      <% @posts.each do |post| %>
        <li class="media">
	  <div class="media-left">
	    <%= image_tag 'http://placehold.it/60x60', :class => "media-object" %>
	  </div> <!-- media-left -->
	  <div class="media-body">
	    <h5 class="media-heading"><%= post.user.email %></h5>
	    <p><%= post.body %></p>
	    <div id="post_<%= post.id %>_likes">
	      <%= render partial: "likes", locals: {post: post} %>
	    </div>
	  </div> <!-- media-body -->
	</li>
      <% end %>
    </ul>
  </div> <!-- col-sm-9 -->
</div> <!-- main-body-row -->

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-9">
    <ul class="media-list">
      <li class="media">
	<div class="media-left">
	  <%= image_tag 'http://placehold.it/60x60', :class => "media-object" %>
	</div> <!-- media-left -->
	<div class="media-body">
	  <h5 class="media-heading"><%= @post.user.email %></h5>
	  <p><%= @post.body %></p>
	  <div id="post_<%= @post.id %>_likes">
	    <%= render partial: "likes", locals: { post: @post } %>
	  </div>
	</div> <!-- media-body -->
      </li>
    </ul>
  </div> <!-- col-sm-9 -->
</div> <!-- row -->

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>